### ISSUE TITLE
Tasks VGS IKT2.

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-migration#110]
#### Tasks.
- [x] Intro course app development
- [x] PR for apps in production. Update to .NET6 and v7.
- [x] Access Altinn Github.
- [x] Access Slack
- [x] Test user TT02?
