### ISSUE TITLE
SIV-1016  - Svar på innkalling øvelse

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-migration#162]
## Innledning

 
 | Beskrivelse av tjenesten |Innsendings skjema som instanieres i sluttbruker sin Altinn innboks av Tjenesteeier.|
| ------------- | ------------- |
| **Tjenestekode** | _Legg inn tjenestekode (ServiceCode)_  |
| **Tjenesteutgavekode**  |  _Legg inn tjenesteutgavekode (ServiceEditionCode)_ |
| **Tjenestetype**  | Innsending/Innsyn/Melding/Samhandling/Formidling/Annen  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://altinn.no/skjemaoversikt/ ....  |
| TUL  | https://tul.altinn.no/ ....  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/ .... |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

### Task

- [x] minOccurs
- [x] Språk (Nynorsk)

**Comment by tonygrimstad** [comment]
@andreas-didriksen Jeg legger inn logo og deployer på nytt til TT02. Antar at det ikke er mer som skal gjøres på appen(?)

**Comment by elwal** [comment]
Prodsatt 27.02.2024
