### ISSUE TITLE
SIV-1010 Taushetserklæring

### ISSUE THREAD

**Issue by tonygrimstad** [Altinn/app-migration#193]
## Innledning

 
 | Beskrivelse av tjenesten | _Vedlegg nr to (sammen med SIV-1015) ved utsendelse av Pålegg av tjenesteplikt i Sivilforsvaret. Genererer ingen statusendring i systemet._ |
| ------------- | ------------- |
| **Tjenestekode** |  5129 |
| **Tjenesteutgavekode**  | 1 |
| **Tjenestetype**  | Innsending |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- __Kun portal-innsending__
- Kun sluttbrukersystem-innsending__
- Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- Ja
- __Nei__

#### Har tjenesten frister eller andre egenskaper?
- Ja
- __Nei__

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
- Preutfylling
- Validering

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | n/a |
| TUL  | http://tul.altinn.cloud/sites/dsb/SIV-1010/Utgave1/default.aspx |
| TT02  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5129 |
| PROD | https://altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5129 |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio |  https://altinn.studio/editor/dsb/siv-1010-taushetserklaering |
| Repos | https://altinn.studio/repos/dsb/siv-1010-taushetserklaering |
| TT02 |  https://dsb.apps.tt02.altinn.no/dsb/siv-1010-taushetserklaering |
| PROD | .... |

```[tasklist]
### Tasks
- [x] Logo
- [x] Påkrevde felt, fjerne minOccurs="0" i datamodellen
- [x] Side 1 Innledning: Justere introtekst(?), ift. "at man må lese lovgivning" - Avventer evt. justert tekst
- [x] Lovsider: Påkrevde avkrysningsbokser, plasseres under lovtekst. Forslag til label på avkrysningsbokser: "Lest"
- [x] Lovsider: Fjerne navigeringsmenyer
- [x] Lovsider: Endre rekkefølge(?) - Avventer tilbakemelding
- [x] Side 6 Taushetserklæring: Lage overskrift (plasseres over "Jeg forstå/Jeg forplikter" - og under PrefillPersonData)
- [x] Side 6 Taushetserklæring: Endre label til tekst med lik formatering som "Og jeg forplikter meg til"
- [x] Side 6 Taushetserklæring: Påkrevd avkrysningsboks flyttes etter tekst (nederst) - Forslag til label på avkrysningsboks: ?
- [ ] DSB godkjent Test
- [x] Mottak/Mapping etc. (Simen) (Simen)
- [x] Språkfiler (Nynorsk)
- [x] Review
- [ ] Produksjon
- [ ] Beholde/Fjerne avkrysningsbokser
- [x] README
```

**Comment by tonygrimstad** [comment]
Oppsummering SIV-1010 (21.9.23)

1. Bytte Logo
2. Side 1 Innledning: Justere introtekst(?), ift. "at man må lese lovgivning" - Avventer evt. justert tekst
3. Lovsider: Påkrevde avkrysningsbokser, plasseres under lovtekst. Forslag til label på avkrysningsbokser: "Lest"
4. Lovsider: Fjerne navigeringsmenyer
5. Lovsider: Endre rekkefølge(?) - Avventer tilbakemelding
6. Side 6 Taushetserklæring: Lage overskrift (plasseres over "Jeg forstå/Jeg forplikter" - og under PrefillPersonData)
7. Side 6 Taushetserklæring: Endre label til tekst med lik formatering som "Og jeg forplikter meg til"
8. Side 6 Taushetserklæring: Påkrevd avkrysningsboks flyttes etter tekst (nederst) - Forslag til label på avkrysningsboks: ?

**Comment by elwal** [comment]
Prodsatt 17.01.24
