### ISSUE TITLE
KRT-1063 Søknad om foretaksbevilling for eiendomsmegling, fremmedinkasso og oppkjøpsinkasso[App navn]

### ISSUE THREAD

**Issue by Ahmed-Ghanam** [Altinn/app-migration#198]
## Innledning

 
 | Beskrivelse av tjenesten | KRT-1063 Søknad om foretaksbevilling for eiendomsmegling, fremmedinkasso og oppkjøpsinkasso |
| ------------- | ------------- |
| **Tjenestekode** | 4637 |
| **Tjenesteutgavekode**  | |
| **Tjenestetype**  | Innsending |
| **Volum**  | |
| **Integrasjon**  | |
 

#### Hvordan benyttes Tjenesten?
- [ ] Kun portal-innsending
- [x] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
![image](https://github.com/Altinn/app-migration/assets/114151129/ac822465-1363-4724-9c72-0235f558f47b)
![image](https://github.com/Altinn/app-migration/assets/114151129/1712740d-c345-4172-9877-b06df9697c95)
![image](https://github.com/Altinn/app-migration/assets/114151129/f2264440-db92-4245-bcdf-4cc46083622f)

## Behov for funksjonalitet
- [X] Flytte skjema til Altinn 3

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  https://altinn.studio/repos/ttd/tilflytter-sogndal-lf  |
| Altinn 3.0 (test)  | https://krt.apps.tt02.altinn.no/krt/krt-1063a-1/ |
| Altinn 3.0 (prod)  | .... |

### Tasks:
- [x]  Rebuild the summary page
- [x] Rebuild the attachments page
- [x] Update the data model and its version
- [x] Use different tag lists depending on the application type
- [x] Translate the Bokmål to Nynorsk and update the options lists
- [x] Find why the element '1.3 Opplys om kjedetilknytning' is disappeared in the test environment
- [ ] Send the application to production.

**Comment by elwal** [comment]
Produksjonssatt 22.08.2024
