### ISSUE TITLE
SIV-1014 Søknad om midlertidig fritak for tjeneste eller varig fritak fra tjenesteplikt i Sivilforsvaret

### ISSUE THREAD

**Issue by tonygrimstad** [Altinn/app-migration#199]
## Innledning

 | Beskrivelse av tjenesten | _Skjemaet initieres av en ansatt, eller et foretak som representerer den ansatte, som ønsker å søker midlertidig fritak fra tjeneste i Sivilforsvaret i en periode. Sivilforsvaret kan på bakgrunn av søknaden vurdere opphør av tjenesteplikt i Sivilforsvaret._ |
| ------------- | ------------- |
| **Tjenestekode** |   |
| **Tjenesteutgavekode**  |  |
| **Tjenestetype**  | Innsending/Innsyn/Melding/Samhandling/Formidling/Annen  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- __Kun portal-innsending__
- Kun sluttbrukersystem-innsending
- Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- Ja
- __Nei__

#### Har tjenesten frister eller andre egenskaper?
- Ja
- __Nei__

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
- Preutfylling
- Validering
- Oppslag

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.studio/editor/dsb/siv-1014-fritak |
| Repos | https://altinn.studio/repos/dsb/siv-1014-fritak |
| TT02  | https://dsb.apps.tt02.altinn.no/dsb/siv-1014-fritak/ |
| PROD | .... |

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/direktoratet-for-samfunnssikkerhet-og-beredskap/soknad-om-midlertidig-fritak-for-tjeneste-eller-varig-fritak-fra-tjenesteplikt-i-sivilforsvaret/ |
| TUL | http://tul.altinn.cloud/sites/dsb/SIV-1014/Utgave1/default.aspx |
| TT02  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5142 |
| PROD | https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5142 |

```[tasklist]
### Tasks
- [x] Første utkast
- [x] Logo
- [x] Endre overskrift fra "Skriv en redegjørelse for søknaden" til "Redegjørelse for søknaden"
- [x] Vedlegg, samme tekst og krav som feks SIV-1005
- [x] Fjerne radioknapp(?)
- [x] Påkrevd fra/til dato (og redegjørelse)
- [x] Påkrevde felt, fjerne minOccurs="0" i datamodellen
- [x] Avklaring på ønskede valideringer/påkrevd
- [x] Vedlegg fungerer ikke (TT02)
- [x] Innlogget som bedrift, skal man som arbeidsgiver kunne søke midlertidig fritak på vegne av tjenestepliktig(?)
- [x] Oppslag på Navn/Person
- [x] Endre/justere tekster
- [x] Avventer avklaring, Skal arbeidsgiver (org) sende inn skjema?
- [x] Endre logo (Medium)
- [x] Valideringstekster i InstanceValidator inn i tekst-ressursfil
- [x] Justere felter: navn, personnummer, datoer
- [x] Oppdatere tekst/lenke på Infoportal (TT)
- [ ] DSB godkjent Test
- [x] Mottak/Mapping etc. (Simen)
- [x] Personsjekk (Person)
- [x] Personsjekk (via Org)
- [x] Språkfiler (Nynorsk)
- [x] Review
- [ ] Produksjon
- [x] README
```

**Comment by tonygrimstad** [comment]
TODO:
- [x] Første utkast
- [ ] Avklaring på ønskede valideringer/påkrevd
- [ ] Vedlegg fungerer ikke (TT02)
- [ ] Design godkjent (DSB)
- [ ] Kode Review

**Comment by elwal** [comment]
Prodsatt 25.01.2024
