### ISSUE TITLE
SIV-1009 Forespørsel vedrørende manglende fremmøte

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#213]
## Innledning

 
 | Beskrivelse av tjenesten | __ |
| ------------- | ------------- |
| **Tjenestekode** | 5127  |
| **Tjenesteutgavekode**  | 1  |
| **Tjenestetype**  | Innsending |

#### Hvordan benyttes Tjenesten?
__Kun portal-innsending__
Kun sluttbrukersystem-innsending
Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
Ja
__Nei__

#### Har tjenesten frister eller andre egenskaper?
Ja
__Nei__

## Skjermbilder

![Image](https://github.com/Altinn/app-migration/assets/65394379/8bee7278-819a-4a14-9925-b37a2fff2751)

![Image](https://github.com/Altinn/app-migration/assets/65394379/3b222186-75c5-49ba-b6c3-2e0001e5cb79)

![Image](https://github.com/Altinn/app-migration/assets/65394379/c478ce9f-7cba-49ba-91a4-b81ac00b1bcf)

![Image](https://github.com/Altinn/app-migration/assets/65394379/faec3c34-de4e-4a78-8808-a917715094b0)

## Behov for funksjonalitet
- Prefill
- Validering

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  | http://tul.altinn.cloud/sites/dsb/SIV-1009/Utgave1/default.aspx  |
| TT02 | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5127 |
| PROD | https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5127 |

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio | https://altinn.studio/editor/dsb/siv-1009-fremmoete/ |
| Repos  | https://altinn.studio/repos/dsb/siv-1009-fremmoete  |
| TT02  | https://dsb.apps.tt02.altinn.no/dsb/siv-1009-fremmoete/ |
| PROD | .... |

```[tasklist]
### Tasks
- [ ] DSB godkjent Test
- [x] Mottak/Mapping etc. (Simen)
- [x] Sette _Required_ på felter, når test er godkjent
- [x] Avklare prefill PLIS (Aktivitet, Dato og Saksbehandlende distrikt)
- [x] Sjekk om vedlegg er påkrevd
- [x] Datamodel --> PascalCase
- [x] Fjerne minOccurs på Plismeta, Ssn, Name og StatementForApplication I datamodel - da de er Required
- [x] Gruppere i Summary og Pdf - "Forklaring på ditt fravær" med vedlegg
- [x] Logo Medium
- [x] Korte ned felter
- [x] Språkfiler (Nynorsk)
- [x] Review
- [ ] Produksjon
- [x] README
```

**Comment by elwal** [comment]
Prodsatt 28.02.24
