### ISSUE TITLE
TAD-5284 Etterdeklarering

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#218]
## Innledning

 
 | Beskrivelse av tjenesten | _Skjema brukes når varemottaker eller dennes representant ønsker å etterdeklarere varer som skulle vært deklarert og tollbehandlet/ stilt til fri disponering ved innførsel_ |
| ------------- | ------------- |
| **Tjenestekode** | 5284  |
| **Tjenesteutgavekode**  | 201901 |
| **Tjenestetype**  | Innsending |

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [X] Nei

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/tolletaten/etterdeklarering/ |
| TUL  | http://tul.altinn.cloud/sites/tad/Etterfort/Etterfort/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=201901&ServiceCode=5284  |

```[tasklist]
### Tasks
```

**Comment by elwal** [comment]
Toll v/Tove Faye-Lund har informert om at dette skjema ikke skal tas i bruk likevel. Fra 1. mars 2024 endrer Tolletaten rutinene ved etterdeklarering av varer og tollrepresentanter må da sende inn deklarasjoner til Tolletaten ved Omberegningsseksjonen på egne særskilte ekspedisjonsenheter.
