### ISSUE TITLE
TAD-4307 Søknad om bindende klassifiseringsuttalelse (BKU) i henhold til gjeldende tolltariff

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#220]
## Innledning

 
 | Beskrivelse av tjenesten | _Bindende klassifiseringsuttalelse (BKU) er et tilbud til importører, eksportører og produsenter som ønsker forhåndsuttalelse om klassifiseringen av en vare i henhold til gjeldende tolltariff._ |
| ------------- | ------------- |
| **Tjenestekode** | 4307  |
| **Tjenesteutgavekode**  | 1 |
| **Tjenestetype**  | Innsending  |

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [X] Nei

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

### TASK:

- [x] Dynamikk for vareeier vs representant
- [x] Dynamikk for Firma vs Person
- [x] Person lookup
- [x] Organisation lookup
- [x] Validering av felter, epost, telefon osv. 
- [x] Dropdown liste med land
- [x] Dynamikk med vareprøver
- [x] Emballasje type alternativer
- [x] Fikse UI så det ser pent ut
- [x] Dynamikk når man har satt inn både orgnr og personnummer.
- [x] Språkfiler
- [ ] Review

### Test feeedback:
- [ ] Legge til riktig Policy tilgang før deploy
- [ ] Forskjellig dynamikk hvis privatperson eller virksomhet. 
- [ ] Noe data forsvinner, vareeier blir ikke med på pdf. 
- [ ] Email forsvinner

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/tolletaten/soknad-om-bindende-klassifiseringsuttalelse-bku-i-henhold-til-gjeldende-tolltariff/ |
| TUL  | http://tul.altinn.cloud/sites/tad/RD-0009/RD-0009/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=4307 |

**Comment by elwal** [comment]
Produksjonssatt 04.06.2024. Ferdigstilt av Tolletaten.
