### ISSUE TITLE
KRT-1172 Rapportering av ICAAP for finansforetak

### ISSUE THREAD

**Issue by Ahmed-Ghanam** [Altinn/app-migration#228]
## Innledning

 
| Beskrivelse av tjenesten | KRT-1172 Rapportering av ICAAP for finansforetak |
| ------------- | ------------- |
| **Tjenestekode** | 5508 |
| **Tjenesteutgavekode**  |  |
| **Tjenestetype**  | Innsending |
| **Volum**  |  |
| **Integrasjon**  |  |
 

#### Hvordan benyttes Tjenesten?
- [ ] Kun portal-innsending
- [x] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja.
- [X] Nei

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
![image](https://github.com/Altinn/app-migration/assets/114151129/9b53798a-8bfc-4fc4-a362-7a3e634faeb7)
![image](https://github.com/Altinn/app-migration/assets/114151129/e9a05d71-c9db-48b7-986d-0d7fc0c8e559)
![image](https://github.com/Altinn/app-migration/assets/114151129/adb22910-2f4b-4d13-9a79-c36318d4f999)
----------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/Altinn/app-migration/assets/114151129/bc26e798-e084-48c0-8a48-551981e9195a)
![image](https://github.com/Altinn/app-migration/assets/114151129/8bf7f873-d9b5-4892-87fd-27598c1a9128)
----------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/Altinn/app-migration/assets/114151129/bf75dbad-7ad3-4f2a-8c45-2a010905bb28)
![image](https://github.com/Altinn/app-migration/assets/114151129/1ce7e7ba-e515-4e2f-9070-e724c3254dee)
![image](https://github.com/Altinn/app-migration/assets/114151129/de8172a1-a6a1-45d0-a54f-ad0347aa7c4f)

## Behov for funksjonalitet
Flytting av skjema til Altinn 3

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.studio/repos/krt/krt-1172a-1 |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

### Tasks:
- [x] Update owner and logo.
- [ ] Rebuild the information page.
- [ ] Rebuild the summary page.
- [ ] Translate the app to Bokmål, Nynorsk and English.
- [ ] Update the data model version whenever the data model is changed.
- [ ] Send the application to production.

**Comment by elwal** [comment]
Skjema produksjonssatt 5.01.2024.
