### ISSUE TITLE
Tilskudd til økt digital deltakelse og kompetanse 

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#246]
## Innledning

| Beskrivelse av tjenesten      | _Søknadsskjemaet for å søke om tilskudd for å legge til rette for etablering av et lavterskel veiledningstilbud hvor personer med liten eller ingen digital kompetanse kan få hjelp og veiledning._ |
| ----------------------------- | --------------------------- |

Mer info om ordningen: https://www.regjeringen.no/no/tema/statlig-forvaltning/it-politikk/tilskudd-til-okt-digital-deltakelse-og-kompetanse-i-2024/tilskudd-til-okt-digital-deltakelse-og-kompetanse-i-2024/id2995510/

Søknadsfristen er fredag 3. november 2024

#### Hvordan benyttes Tjenesten?
Kun portal-innsending (J/N):  J
Kun sluttbrukersystem-innsending (J/N): N 
Både portal- og sluttbrukersystem-innsending (J/N): N

Har tjenesten underskjema/skjemasett (J/N)  N

## Skjermbilder

<details>

![image](https://github.com/Altinn/app-migration/assets/29474941/ebdeb397-23ba-4755-a45c-ae53eb900b8b)
![image](https://github.com/Altinn/app-migration/assets/29474941/188cf003-1b22-4730-93d6-0f3084541e04)
![image](https://github.com/Altinn/app-migration/assets/29474941/84c622fa-a1f1-4f1e-818e-9e481e187662)
![image](https://github.com/Altinn/app-migration/assets/29474941/828551e6-9a03-4edd-a5c4-408e8116fa0b)

</details>

## Behov for funksjonalitet
> Fyll ut

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  https://altinn.studio/editor/digdir/tilskudd-dig-delt-komp/overview  |
| Repos  |  https://altinn.studio/repos/digdir/tilskudd-dig-delt-komp  |
| Altinn 3.0 (Test/TT02)  |  https://digdir.apps.tt02.altinn.no/digdir/tilskudd-dig-delt-komp/  |  

```[tasklist]
### Tasks
- [x] Lage Altinn 3 skjema
- [x] Verifisere alle felt i skjema: valideringer, påkrevde felt, hjelpetekster, layout
- [ ] https://github.com/Altinn/app-migration/issues/262
- [x] Mottak av skjema (webSak)
- [x] Lage infoside Altinn skjemakatalog TT02
- [x] Lage infoside Altinn skjemakatalog PROD
- [x] Verifisere hele prosessen fra initiering i Altinn til mottak i webSak
- [x] Sende inn oppdatert databehandler-/samarbeids-avtale (ikke relevant)
- [x] Oversettelse til nynorsk
- [x] Verifisering i Prod
```

## TODO

- [x] Logo
- [x] Språkfiler
- [x] Applikasjonsprosess
- [x] Sikkerhetsnivå
- [x] Aktørtype (organisasjon/person/konkursbo...)
- [x] Rollekrav

### Code Review  

<details>

**Textresources:**
- [ ] Check app logo
- [ ] Check that it has Alternative text for logo
- [ ] Check Appowner
- [ ] Check Camelcase on id  

**Layout files:**
- [ ] Camelcase on id
- [ ] Use Groups that can be reused in summary and pdf
- [ ] If app has an attachment component it should have the same values such as min and max count as in applicationmeta data file.
- [ ] Check that it has a file called 01Intro
- [ ] Check that it has a file called 99Summary
- [ ] Check that it has a pdfReceipt file
- [ ] Check Grid and inner grid and make sure it has both xs: and md:  

**Applicationmetadata:**
- [ ] Logo
- [ ] Check that displayAppOwnerNameInHeader: false
- [ ] Logo "size" same as the other applications  
 
**App.csproj:**
- [ ] Make sure PackageReference version = 7.15.1  

**Data model:**
- [ ] Delete minOccurs on required fields.
- [ ] Pascal case on name in data model  

**Options file:**
- [ ] Make sure all plain text is referred to though text resource id  

**Logic files:**
- [ ] Make sure all plain text is referred to though text resource id
- [ ] Make sure all custom service implementations is added in Program.cs

</details>

**Comment by elwal** [comment]
Produksjonssatt 24.04.2024
