### ISSUE TITLE
Registrering av kontaktpersoner og valgansvarlige til valggjennomføringen

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#256]
## Innledning

 
 | Beskrivelse av tjenesten | Skjema for registrering av kontaktpersoner og valgansvarlige i EVA (Elektronisk ValgAdministrasjon) |
| ------------- | ------------- |
| **Tjenestekode** | 4600  |
| **Tjenesteutgavekode**  | 1 |  
 

#### Hvordan benyttes Tjenesten?
Kun portal-innsending (J/N):  Ja

Har tjenesten underskjema/skjemasett (J/N): Nei 

Skjema instansieres i innboksen til kommuner og statsforvaltere. Åpnes ikke fra skjemakatalog.

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her. 
![image](https://github.com/Altinn/app-migration/assets/75472603/c07ea3be-aeaa-42fa-bb78-a0b6d9aa9756)

#### Sikkerhetsnivå: 
3

#### Aktører:
Virksomhet
Underenhet

#### Steg:
Utfylling 
Signering

#### Rolle:
UTINN - Utfyller/innsender

## Behov for funksjonalitet
> Fyll ut

#### Endringer i skjema
[Forslag til endringer i Altinn-skjema (1).docx](https://github.com/Altinn/app-migration/files/14276307/Forslag.til.endringer.i.Altinn-skjema.1.docx)

#### Kravspek
Ligger noe info i "Huskeliste" her:
[Orginal: Kravspek_Registrering av delegert fullmakt og valgansvarlige.xlsx](https://github.com/Altinn/app-migration/files/14258969/Kravspek_Registrering.av.delegert.fullmakt.og.valgansvarlige.xlsx)
[Oppdatert  Kravspek_Registrering.av.delegert.fullmakt.og.valgansvarlige.7 (2).xlsx](https://github.com/Altinn/app-migration/files/15462072/Kravspek_Registrering.av.delegert.fullmakt.og.valgansvarlige.7.2.xlsx)

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://info.altinn.no/skjemaoversikt/valgdirektoratet/registrering-av-valgansvarlige/ |
| TUL  | http://tul.altinn.cloud/sites/valg/VALG-01/VALG-01/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=4600 |  

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  ....  |
| Altinn 3.0 (test)  |  ....  |  

## Tasks  

- [x] Logo
- [ ] Språkfiler
- [x] Applikasjonsprosess
- [x] Sikkerhetsnivå
- [x] Aktørtype (organisasjon/person/konkursbo...)
- [x] Rollekrav
- [ ] Godkjent i test av tjenesteeier 
- [ ] Review
- [ ] Produksjon
- [ ] Oppdatere tekst/lenke på Infoportal (TT)

#### Code Review  

**Textresources:**
- [x] Check app logo
- [x] Check that it has Alternative text for logo
- [x] Check Appowner
- [x] Check Camelcase on id  

**Layout files:**
- [x] Camelcase on id
- [x] Use Groups that can be reused in summary and pdf
- [ ] If app has an attachment component it should have the same values such as min and max count as in applicationmeta data file.
- [x] Check that it has a file called 01Intro
- [x] Check that it has a file called 99Summary
- [x] Check that it has a pdfReceipt file
- [ ] Check Grid and inner grid and make sure it has both xs: and md:  

**Applicationmetadata:**
- [x] Logo
- [x] Check that displayAppOwnerNameInHeader: false
- [x] Logo "size" same as the other applications  
 
**App.csproj:**
- [ ] Make sure PackageReference version = 7.15.1  

**Data model:**
- [ ] Delete minOccurs on required fields.
- [ ] Pascal case on name in data model  

**Options file:**
- [ ] Make sure all plain text is referred to though text resource id  

**Logic files:**
- [ ] Make sure all plain text is referred to though text resource id
- [ ] Make sure all custom service implementations is added in Program.cs

**Comment by elwal** [comment]
Produksjonssatt 11.09.24
