### ISSUE TITLE
INT-1017 Oppdatering av personopplysninger (Internasjonalt)

### ISSUE THREAD

**Issue by tonygrimstad** [Altinn/app-migration#266]
## Innledning

| Beskrivelse av tjenesten      | _Legg inn kort beskrivelse_ |
| ----------------------------- | --------------------------- |
| **Volum**                     | _Ca antall transaksjoner pr. år_  |
| **Planlagt produksjonssatt**  | _dd.mm.åå_                  |

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året, hendelsesbasert._

## Behov for funksjonalitet
> Fyll ut

## Lenker og filer

| Område                  | Lenke     |
| -------------------    | --------- |
| Altinn Studio           |https://altinn.studio/editor/dsb/int-1017-personopplysninger/overview|
| Altinn Studia Repos|https://altinn.studio/repos/dsb/int-1017-personopplysninger|
| Altinn 3.0 (test) |           |

```[tasklist]
### Tasks
- [ ] Lage Altinn 3 skjema
- [ ] Verifisere alle felt i skjema: valideringer, påkrevde felt, hjelpetekster, layout
- [ ] Konfigurere mottak (altinn-forms)
- [ ] Prefill-data i initiering fra PLIS: Mapping (saft)
- [ ] Kall for person-sjekk i skjema
- [ ] Infoside Altinn skjemakatalog TT02
- [ ] Infoside Altinn skjemakatalog PROD
- [ ] Verifisere hele prosessen fra initiering i PLIS/Altinn til mottak i Elements/PLIS
- [ ] Sende inn oppdatert databehandler-/samarbeids-avtale
- [ ] Oversettelse til nynorsk
- [ ] Verifisering i Prod
- [ ] Sanere Altinn 2 skjema i PROD
```

**Comment by tonygrimstad** [comment]
Utviklingsprosessen på dette skjemaet (og andre DSB skjema) fasiliteres i DSB sin Jira. Så historikken ligger der (og kun delvis her).
Skjemaet er ganske ferdig utviklet, og det pågår testing (over lang tid).
Vi avventer nå pågående ende-til-ende-test hos DSB.
Vi/Tony har en løpende (privat) dialog på Slack med DSB's utvikler, og følger oppgavene i Jira.
