### ISSUE TITLE
Skattemelding for næringsdrivende (Sirius)

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-migration#7]
Skatteetaten forenkler skattemeldingen for næringsdrivende. Målet er at det skal bli enklere og mer effektivt å levere riktige opplysninger med bedre kvalitet.

[Les mer](https://www.skatteetaten.no/bedrift-og-organisasjon/skatt/skattemelding-naringsdrivende/ny-skattemelding/)

## Brukerhistorier
- En bruker kan laste ned forhåndsutfylt skattemelding.xml og næringsoppgave.xml gjennom API.
- En bruker kan validere næringsoppgave.xml før data sendes inn for egen organisasjon eller klient
- En organisasjon kan validere næringsmelding.xml før data sendes inn til egen organisasjon eller oppdragsgiver
- En bruker kan sende inn skattedata(næringsoppgave.xml, skattemelding.xml) gjennom api for egen organisasjon eller oppdragsgiver
- en organisasjon kan sende inn skattedata gjennom API for egen organisasjon eller klient
- Søknad legger til PDF-utskrift av næringmelding til instansen
- SKD kan gi tilbakemelding til parten om det endelige valideringsresultatet. Tilbakemeldingen er en XML + en kvittering i PDF-format

### Godkjenning
Autentisering for sluttbrukere som bruker sluttbrukersystem vil gjøres gjennom ID-porten. Sluttbrukersystemer vil presentere en nettleser der brukeren kan autentisere.

#### Oppgaver
- [ ] ID-porten må oppdateres for å støtte disse scenariene
- [ ] Eksempelimplementering for sluttbrukersystem må være tilgjengelig
- [ ] Sluttbrukersystemer må oppdateres
- [ ] API for å bytte ID-porten-token til Altinn-token må opprettes Altinn/altinn-studio#3291
- [x] Userprofile API i bridge for ssn Altinn/altinn-studio#3840
- [x] UserProfile API i plattform for ssn Altinn/altinn-studio#3841

Maskinporten skal brukes til å autentisere organisasjoner.

- [ ] Maskinportend exchange API må oppdateres for å støtte tradisjonelle organisasjoner Altinn/altinn-studio#3787

### Autorisasjon
Sluttbrukere og organisasjoner vil bli autorisert mot regler for søknad.

- [ ] Behov for å støtte autorisasjon av organisasjoner. Oppdater roller API og kontekstbehandler Altinn/altinn-authorization#7

Det kan være behov for en måte for bruker som logger inn på at de kan velge hvilke meldere/apper sluttbrukersystemet har lov til å ringe til Altinn basert på

- [ ] Autorisasjon av omfang basert på valgt melder ved innlogging på ID-porten

### Hent skattemelding APP
hent skattemelding-appen vil fungere som en proxy for hent skattemelding API
- [ ] Definer hvordan nettverk kan settes opp Altinn/altinn-studio#150

### Valideringsapp
Valideringsappen vil fungere som en proxy for validerings-API

- [ ] Definer hvordan hemmeligheter kan nås fra app. (url til API, legitimasjon) Altinn/altinn-studio#1127
- [ ] Definer hvordan nettverk kan settes opp Altinn/altinn-studio#150

### Sirius-appen
Sirius-appen vil bli definert som en "rapporteringstjeneste" med en enkel datamodell og nødvendige binære vedlegg.

#### Prosess
Prosessen for Sirius-appen ville være

- Data : Systemer kan laste opp skjemadata og vedlegg
- Bekreftelse: Systemer og brukere kan laste ned PDF lastet opp fra SKD og godkjenne
- Tilbakemelding

**Datavisning**
![bilde](https://user-images.githubusercontent.com/13309071/77439782-c77dba00-6de7-11ea-87a3-55609463b19d.png)

**Bekreftelsesvisning**
![bilde](https://user-images.githubusercontent.com/13309071/77440104-30fdc880-6de8-11ea-850e-81a742450eb5.png)

**Tilbakemeldingsvisning**
![bilde](https://user-images.githubusercontent.com/13309071/77442345-a5d20200-6dea-11ea-8338-8818c49863f0.png)

**Kvittering**
![bilde](https://user-images.githubusercontent.com/13309071/77529583-2dbe1780-6e90-11ea-8cef-8a408b612f26.png)

- [x] Oppdater søknadsmal for å støtte en prosess med data og bekreftelsesoppgave Altinn/altinn-studio#1379
- [ ] Definer hva som skal skje hvis brukeren sender skjemaet tilbake til skjemautfylling. Bør PDF slettes da. Altinn/altinn-studio#1379
- [ ] Definer hvordan appen kan hindre bruker/systemer i å fullføre instans hvis PDF ikke er lastet opp Altinn/altinn-studio#1379
- [ ] Legg til støtte for tilbakemeldingstrinn Altinn/altinn-studio#2047 Altinn/altinn-studio#3843
- [ ] Oppdater meldingsboksen for å støtte tilbakemeldingsoppgaven Altinn/altinn-studio#3842

#### Gui
Data vil bli sendt fra sluttbrukersystemet, men vi må håndtere at brukere klikker på forekomst i meldingsboksen. Den foreslåtte løsningen er å lage en enkel GUI som presenterer de viktigste feltene fra datamodellen.

- [ ] lag datamodell for app (SKD må definere dette)
- [ ] Bekreft at de nødvendige komponentene er tilgjengelige for å lage gui for datamodell (SKD + Altinn)

Når forekomsten er i bekreftelsesoppgaven kan brukeren laste ned
- PDF for hovedskjemaet. Generert av Altinn
- Binære filer vedlagt
- PDF generert av SKD

- [ ] Lag bekreftelsesvisning som presenterer relevante lenker Altinn/altinn-studio#981

Når forekomsten er tilbakemeldingsvisning, må den ha informasjon om det og avvente

- [ ] Lag tilbakemeldingsvisning Altinn/altinn-studio#3843

#### Arrangementer
SKD må varsles i følgende hendelser

- System eller brukere fullfører dataoppgave på en forekomst
- System eller brukere fullfører konformasjonsoppgave på en forekomst

Foreløpig støtter vi bare at ORG kan spørre API for hendelser-

Vi må analysere og konfigurere/bygge de jevndrevne arkitekturkomponentene
som vil gi. Detaljer i Altinn/altinn-studio#1783

### Gebyrtilbake
SKD må gi tilbakemelding til parten når instansen er endelig validert.
Den foreslåtte løsningen er at SKD laster opp et dokument med tilbakemelding

- [ ] Lag API for å laste opp tilbakemelding Altinn/altinn-studio#2389 Altinn/altinn-studio#2057

## Fullfør prosess
Diagrammet nedenfor prøver å vise hele Sirius-prosessen
![bilde](https://user-images.githubusercontent.com/13309071/81046293-56d2be80-8eb8-11ea-91ee-351112a1d6a6.png)

## Skal analyseres

**Comment by AinaEngen** [comment]
@TheTechArch - hva er status på denne? Kan den lukkes? cc: @elwal
